version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-development:
        dependency-type: development
  - package-ecosystem: pip
    directory: "/youtube_downloader"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/youtube_downloader"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
